baseURL = "https://dmatuteb.github.io"
languageCode = "en-us"
title = "Daniel Matute's website"
theme = "portfolio"

[params]
  indexPCImage = "/img/me.jpg"
  cv = "/pdf/DANIEL_MATUTE_EN.pdf"
  github = "https://github.com/dmatuteb"
  linkedin = "https://www.linkedin.com/in/daniel-matute-burgos-0644471aa/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

    [menu]
      [[menu.main]]
        identifier = "Home"
        url = "/"
        name = "Home"
        weight = 1

  [languages.es]
    contentDir = "content/es"
    languageName = "Espa√±ol"
    weight = 2

    [languages.es.menu]
     [[languages.es.menu.main]]
       url = "/"
       name = "Inicio"
       weight = 2

    [languages.es.params]
      cv = "/pdf/DANIEL_MATUTE_ES.pdf"
